name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build docker image for testing the client
        run: docker build -f ./client/Dockerfile.dev -t tonivrd/client-test ./client
        
      - name: Run tests
        run: docker run -e CI=true tonivrd/client-test npm run test

  build:
    name: Build docker images and push to docker repo
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build all docker images for the project
        run: python -u ./scripts/build.py

      - name: Push all docker images to repo
        run: python -u ./scripts/push.py
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
